#!/bin/bash
#
# 20200404 Jens Heine
# 20200413 Jens Heine: FTPS mode enabled
# 20200710 Jens Heine <binbash@gmx.net>
#          Dennis Brossat <dennis.brossat@email.de>
#          Benjamin Heine <benjaminheine@gmx.net>
#
# airback - backup your mobile device over wifi
#
#set -e
#set -x

#
# VARIABLES
#
# Base directory for airback
VERSION="20200714"
AIRBACK_ROOT_DIR="$HOME/airback"
AIRBACK_CONFIG_FILE="${AIRBACK_ROOT_DIR}/airback.conf"
DEBUG=0
REMOTE_IS_ALREADY_MOUNTED=0
VERBOSITY=""
RSYNC_CMD="nice -n 20 rsync -${VERBOSITY}rultR --chmod=774"
NMAP_CMD="nice -n 20 nmap "
USAGE_INFO_TEXT="

        airback by Jens Heine <binbash@gmx.net> 2020
                   and Dennis Brossat <dennis.brossat@email.de>
                   and Benjamin Heine <benjaminheine@gmx.net>

USAGE

        airback OPTIONS

OPTIONS
        -c            : Show config file
        -d            : Show debug infos
        -h            : Show usage information
	-S [VARIABLE] : set VARIABLE to set in config file (use together with -V)
	-V [VALUE]    : set VALUE to set variable to value in config file (use together with -S)
        -v            : Show program version

"


#
# FUNCTIONS
#
# Args: IP PORT
checkForRunningPortServer() {
	logDebug "Checking for mobile..."
	[ "$1" -a "$2" ] || {
		logInfo "Host or port missing."
		exit 1
	}
	${NMAP_CMD} ${1} -p ${2} | grep "open" >/dev/null 2>&1
	RET_VAL=$?
	[ "${RET_VAL}" -eq 0 ] && {
		logDebug "Mobile "$1" port "$2" found."
		return 0
	}
	logDebug "Mobile "$1" port "$2" not found."
	return 1
}

function logInfo() {
	echo "INFO  - `date "+%Y%m%d %H:%M:%S"` : ${1}"
}

function logDebug() {
	[ $DEBUG -eq 0 ] && return
	echo "DEBUG - `date "+%Y%m%d %H:%M:%S"` : ${1}"
}

function checkLocalMobileMountpointBase() {
	[ -d ${LOCAL_MOBILE_MOUNTPOINT_BASE} ] || {
        	logDebug "Local mobile mountpoint base folder not found: ${LOCAL_MOBILE_MOUNTPOINT_BASE}"
	        mkdir -p ${LOCAL_MOBILE_MOUNTPOINT_BASE} >/dev/null 2>&1
	        RET_VAL=$?
	        [ $RET_VAL -ne 0 ] && {
        	        logInfo "Error creating local mobile mountpoint base folder."
                	exit 1
	        }
	        logInfo "Local local mobile mountpoint base folder ${LOCAL_MOBILE_MOUNTPOINT_BASE} created."
	}
}

function checkLocalBackupTargetBaseDir() {
	[ -d ${LOCAL_BACKUP_TARGET_BASE_DIR} ] || {
	        logDebug "Local backup target base folder not found: ${LOCAL_BACKUP_TARGET_BASE_DIR}"
	        mkdir -p ${LOCAL_BACKUP_TARGET_BASE_DIR} >/dev/null 2>&1
	        RET_VAL=$?
	        [ $RET_VAL -ne 0 ] && {
	                logInfo "Error creating local backup target base folder ${LOCAL_BACKUP_TARGET_BASE_DIR}."
	                exit 1
	        }
	        logInfo "Local backup target base folder ${LOCAL_BACKUP_TARGET_BASE_DIR} created."
	}
}

function mountMobile() {
	logDebug "Trying to mount mobile."
	df -h|grep ${LOCAL_MOBILE_MOUNTPOINT_BASE} 2>&1 >/dev/null
	REMOTE_IS_ALREADY_MOUNTED=$?
	if [ "$REMOTE_IS_ALREADY_MOUNTED" != 0 ];then
		curlftpfs -r -o ssl,no_verify_hostname,no_verify_peer,user=${MOBILE_USER}:${MOBILE_USER_PASS} ftps://${MOBILE_HOST}:${MOBILE_PORT}/ ${LOCAL_MOBILE_MOUNTPOINT_BASE}
		RET_VAL=$?
		[ "$RET_VAL" -ne 0 ] && {
			logDebug "Mobile could not be mounted."
			return 1
		}
		logDebug "Mobile mounted."
		return 0
	else
		logDebug "Mobile is already mounted."
		return 0
	fi
}

function doBackup() {
	mountMobile || {
		logInfo "Error: mounting mobile failed."
		return 1
	}
	cd ${LOCAL_MOBILE_MOUNTPOINT_BASE}

#	set +e
	#-------------Copy Folders START-------------------#
	logDebug  "Syncing DCIM/Camera..."
	${RSYNC_CMD} DCIM/Camera ${LOCAL_BACKUP_TARGET_BASE_DIR}
	#--------------------------------------------------#
	logDebug  "Syncing DCIM/Screenshots..."
	${RSYNC_CMD} DCIM/Screenshots ${LOCAL_BACKUP_TARGET_BASE_DIR}
	#--------------------------------------------------#
	logDebug  "Syncing Pictures..."
	${RSYNC_CMD} Pictures ${LOCAL_BACKUP_TARGET_BASE_DIR}
	#--------------------------------------------------#
	logDebug  "Syncing Movies..."
	${RSYNC_CMD} Movies ${LOCAL_BACKUP_TARGET_BASE_DIR}
	#--------------------------------------------------#
	logDebug  "Syncing Music..."
	${RSYNC_CMD} Music ${LOCAL_BACKUP_TARGET_BASE_DIR}
	#--------------------------------------------------#
	logDebug  "Syncing Telegram..."
	${RSYNC_CMD} Telegram ${LOCAL_BACKUP_TARGET_BASE_DIR}
	#--------------------------------------------------#
	logDebug  "Syncing WhatsApp..."
	${RSYNC_CMD} WhatsApp ${LOCAL_BACKUP_TARGET_BASE_DIR}
	#--------------------------------------------------#
	logDebug  "Syncing Signal..."
	${RSYNC_CMD} Signal ${LOCAL_BACKUP_TARGET_BASE_DIR}
	#-------------Copy Folders END---------------------#
#	set -e

	cd - 2>&1 >/dev/null
	logDebug  "Unmounting mobile filesystem..."
	sleep ${SLEEP_TIME_TO_WAIT_FOR_MOBILE_FLUSH}
	fusermount -u ${LOCAL_MOBILE_MOUNTPOINT_BASE}
	RET_VAL=$?
	[ $RET_VAL -ne 0 ] && {
		logDebug "Error unmounting mobile."
		return
	}
	logDebug "Mobile unmounted."
}

function createDefaultConfigFile() {
	[ -d ${AIRBACK_ROOT_DIR} ] || {
		logDebug "Root folder not found."
		logInfo "Creating root folder: ${AIRBACK_ROOT_DIR}"
		mkdir -p ${AIRBACK_ROOT_DIR}
	}
	logInfo "Creating default conf file ${AIRBACK_CONFIG_FILE}"
echo '
#
# airback.conf
#
# 20200709 jens heine <binbash@gmx.net>
#          Dennis Brossat <dennis.brossat@email.de>
#          Benjamin Heine <benjaminheine@gmx.net>
#
# Configuration file for airback - backup your mobile device over wifi
#

# Local folder where remote device will be mounted
LOCAL_MOBILE_MOUNTPOINT_BASE="${AIRBACK_ROOT_DIR}/mnt"
# Local folder where remote files will be saved
LOCAL_BACKUP_TARGET_BASE_DIR="${AIRBACK_ROOT_DIR}/backup"
# Remote access configuration
# Note: Enable implicit ssl mode on server
MOBILE_HOST="192.168.1.21"
MOBILE_PORT="10000"
MOBILE_USER="ftpuser"
MOBILE_USER_PASS="pass"
# Run airback as a daemon who polls for the mobile
RUN_AS_DAEMON="1"
# Polling interval to find the mobile in seconds
SEARCH_MOBILE_INTERVAL_SEC="5"
# Interval for doing backups
BACKUP_INTERVAL_SEC="600"
SLEEP_TIME_TO_WAIT_FOR_MOBILE_FLUSH="3"
' > ${AIRBACK_CONFIG_FILE}	
}

function checkForCommand() {
	[ ! "${1}" ] && {
		logDebug "Error: no command given to check."
		return 0
	}
	logDebug "Checking if ${1} is installed."
        which "${1}" >/dev/null 2>&1
        RET_VAL=$?
        [ "$RET_VAL" -ne 0 ] && {
                logInfo "Error: ${1} not found." 
                logInfo "Please install ${1}. For example: apt-get install ${1}" 
		return 1
        }
	logDebug "Success: command ${1} is installed."
	return 0
}

#
# check if all needed tools are available
#
function checkDependencies() {
	DEPENDENCY_ERRORS=0
	logDebug "Checking dependencies..."

	checkForCommand "rsync"
	let DEPENDENCY_ERRORS=$DEPENDENCY_ERRORS+$?
	checkForCommand "nice"
	let DEPENDENCY_ERRORS=$DEPENDENCY_ERRORS+$?
	checkForCommand "nmap"
	let DEPENDENCY_ERRORS=$DEPENDENCY_ERRORS+$?
	checkForCommand "curlftpfs"
	let DEPENDENCY_ERRORS=$DEPENDENCY_ERRORS+$?

	[ $DEPENDENCY_ERRORS -eq 0 ] && {
		logDebug "Dependency check OK."
		return 0
	} 
	logDebug "Dependency check had errors."
	return 1
}

function showUsage() {
	echo "$USAGE_INFO_TEXT"
}

function showVersionInfo() {
	echo
	echo "airback version: $VERSION"
	echo
}

function showConfigFile() {
	echo 
	echo " Print airback configuration file"
	echo " Filename: ${AIRBACK_CONFIG_FILE}"
	echo
	cat ${AIRBACK_CONFIG_FILE}
}

function setVariableInConfigFile() {
        [ ! "${1}" ] && {
                logDebug "Error: Variable name missing."
                return 1
        }
        [ ! "${2}" ] && {
                logDebug "Error: Value for variable missing."
                return 1
        }
	grep "${1}" "${AIRBACK_CONFIG_FILE}" >/dev/null 2>&1
	RET_VAL=$?
	[ "$RET_VAL" -ne 0 ] && {
		logDebug "ERROR: Variable ${1} not found in configfile ${AIRBACK_CONFIG_FILE}"
		return 1
	}
	logDebug "Setting new value for variable in config file:"
	logDebug "Variable : ${1}"
	logDebug "Value    : ${2}"
	SED_PARAM="s#${1}=.*#${1}=${2}#g"
	logDebug "SED_PARAM=$SED_PARAM"
	sed -i "$SED_PARAM" ${AIRBACK_CONFIG_FILE}
	RET_VAL=$?
	if [ "$RET_VAL" -eq 0 ];then
		logDebug "Variable ${1} set to ${2} in configfile ${AIRBACK_CONFIG_FILE}."
		return 0
	else
		logInfo "Error setting variable ${1} to ${2} in configfile ${AIRBACK_CONFIG_FILE}." 
		return 1
	fi
}

function setVariablesInConfigFileFromUserInput() {
	echo
	echo " Please set the variables for your config file."
	echo
	read -p " Enter the IP of your mobile                               : " U_MOBILE_HOST
	read -p " Enter the port mobile ftp service                         : " U_MOBILE_PORT
	read -p " Enter the ftp username                                    : " U_MOBILE_USER
	read -sp " Enter the ftp password                                    : " U_MOBILE_USER_PASS
	echo
	echo    " Enter the local path where your mobile filesystem"
        read -p "  will be mounted to (it will be created if needed)        : " U_LOCAL_MOBILE_MOUNTPOINT_BASE
	echo    " Enter the local path where the files from your mobile"
        read -p "  will be written to (it will be created if needed)        : " U_LOCAL_BACKUP_TARGET_BASE_DIR
	echo    " Should airback run in deamon mode? (0 or 1 default is 1)"
	echo    "  If set to 1 airback will periodically check if your"
        read -p "  mobile is reachable in the network                       : " U_RUN_AS_DAEMON
	read -p " Set interval in s to search for your mobile (default 30)  : " U_SEARCH_MOBILE_INTERVAL_SEC
	read -p " Set backup interval in s  (default 600)                   : " U_BACKUP_INTERVAL_SEC
	echo
	# set default values
	U_RUN_AS_DAEMON=${U_RUN_AS_DAEMON:-1}
	U_SEARCH_MOBILE_INTERVAL_SEC=${U_SEARCH_MOBILE_INTERVAL_SEC:-30}
	U_BACKUP_INTERVAL_SEC=${U_BACKUP_INTERVAL_SEC:-600}
	logDebug "U_MOBILE_HOST                  : $U_MOBILE_HOST"
	logDebug "U_MOBILE_PORT                  : $U_MOBILE_PORT"
	logDebug "U_MOBILE_USER                  : $U_MOBILE_USER"
	logDebug "U_MOBILE_USER_PASS             : $U_MOBILE_USER_PASS"
	logDebug "U_LOCAL_MOBILE_MOUNTPOINT_BASE : $U_LOCAL_MOBILE_MOUNTPOINT_BASE"
	logDebug "U_LOCAL_BACKUP_TARGET_BASE_DIR : $U_LOCAL_BACKUP_TARGET_BASE_DIR"
	logDebug "U_RUN_AS_DAEMON                : $U_RUN_AS_DAEMON"
	logDebug "U_SEARCH_MOBILE_INTERVAL_SEC   : $U_SEARCH_MOBILE_INTERVAL_SEC"
	logDebug "U_BACKUP_INTERVAL_SEC          : $U_BACKUP_INTERVAL_SEC"
	[ ! "$U_MOBILE_HOST" -o ! "$U_MOBILE_PORT" -o ! "$U_MOBILE_USER" \
 	  -o ! "$U_MOBILE_USER_PASS" -o ! "$U_LOCAL_MOBILE_MOUNTPOINT_BASE" \
	  -o ! "$U_LOCAL_BACKUP_TARGET_BASE_DIR" -o ! "$U_RUN_AS_DAEMON" \
	  -o ! "$U_SEARCH_MOBILE_INTERVAL_SEC" \
	  -o ! "$U_BACKUP_INTERVAL_SEC" ] && {
		logInfo "Error: Variables must not be empty." 
		return 1
	}
	logDebug "Setting variables and writing config file..."
	CONFIG_FILE_ERRORS=0
	setVariableInConfigFile "MOBILE_HOST" "${U_MOBILE_HOST}"
        let CONFIG_FILE_ERRORS=$CONFIG_FILE_ERRORS+$?
	setVariableInConfigFile "MOBILE_PORT" "${U_MOBILE_PORT}"
        let CONFIG_FILE_ERRORS=$CONFIG_FILE_ERRORS+$?
	setVariableInConfigFile "MOBILE_USER" "${U_MOBILE_USER}"
        let CONFIG_FILE_ERRORS=$CONFIG_FILE_ERRORS+$?
	setVariableInConfigFile "MOBILE_USER_PASS" "${U_MOBILE_USER_PASS}"
        let CONFIG_FILE_ERRORS=$CONFIG_FILE_ERRORS+$?
	setVariableInConfigFile "LOCAL_MOBILE_MOUNTPOINT_BASE" "${U_LOCAL_MOBILE_MOUNTPOINT_BASE}"
        let CONFIG_FILE_ERRORS=$CONFIG_FILE_ERRORS+$?
	setVariableInConfigFile "LOCAL_BACKUP_TARGET_BASE_DIR" "${U_LOCAL_BACKUP_TARGET_BASE_DIR}"
        let CONFIG_FILE_ERRORS=$CONFIG_FILE_ERRORS+$?
	setVariableInConfigFile "RUN_AS_DAEMON" "${U_RUN_AS_DAEMON}"
        let CONFIG_FILE_ERRORS=$CONFIG_FILE_ERRORS+$?
	setVariableInConfigFile "SEARCH_MOBILE_INTERVAL_SEC" "${U_SEARCH_MOBILE_INTERVAL_SEC}"
        let CONFIG_FILE_ERRORS=$CONFIG_FILE_ERRORS+$?
	setVariableInConfigFile "BACKUP_INTERVAL_SEC" "${U_BACKUP_INTERVAL_SEC}"
        let CONFIG_FILE_ERRORS=$CONFIG_FILE_ERRORS+$?
	[ $CONFIG_FILE_ERRORS -eq 0 ] && {
		logDebug "Setting variables done."
		return 0
        }
	logDebug "Setting variables done with errors." 
	logDebug "Please check config file manually." 
	return 1
}


###################################################################################################
#
# MAIN
#
###################################################################################################

#
# Evaluate arguments
#
ACTION=""
while getopts "cdhS:vV:" options;do
	case "$options" in
		c) showConfigFile
		   exit 0
		   ;;
		d) DEBUG=1
		   VERBOSITY="v"
		   RSYNC_CMD="${RSYNC_CMD} -v"
		   ;;
		h) showUsage
		   exit 0
		   ;;
		S) ACTION="SET_VARIABLE_IN_CONFIG"
		   VAR_NAME=${OPTARG}
		   ;;
		V) ACTION="SET_VARIABLE_IN_CONFIG"
		   VAR_VALUE=${OPTARG}
		   ;;
		v) showVersionInfo
		   exit 0
		   ;;
		*) showUsage
		   exit 0
		   ;;
	esac
done

#
# Process actions
#
if [ "$ACTION" = "SET_VARIABLE_IN_CONFIG" ];then
	echo
	logDebug "Set variable in config file"
	[ ! "$VAR_NAME" -o ! "$VAR_VALUE" ] && {
		echo "Error: Variable name or value missing." 
		echo
		echo "Try -h for help."
		echo
		exit 1
	}
	setVariableInConfigFile "${VAR_NAME}" "${VAR_VALUE}"
	RET_VAL=$?
	[ "$RET_VAL" -ne 0 ] && {
		echo "Error setting ${VAR_NAME} set to ${VAR_VALUE}." 
		echo
		exit 1
	}
	echo "Variable ${VAR_NAME} set to ${VAR_VALUE}"
	echo
	exit 0
fi

#
# Check dependencies
#
checkDependencies || {
	logInfo "Missing dependecies. Please install the missing commands and restart."
	exit 1
}

#
# Check and source config file
#
[ -r ${AIRBACK_CONFIG_FILE} ] || {
	logInfo "Error config file not found: ${AIRBACK_CONFIG_FILE}"
	createDefaultConfigFile
	setVariablesInConfigFileFromUserInput || {
		logInfo "Error: check config file manually: ${AIRBACK_CONFIG_FILE}" 
		exit
	}
}

# Load config file
. ${AIRBACK_CONFIG_FILE}

#
# Check paths
#
checkLocalMobileMountpointBase
checkLocalBackupTargetBaseDir

#
# Go
#
logInfo "Starting airback..."
logInfo "Exit with <strg>C"
while true;do
	checkForRunningPortServer "$MOBILE_HOST" "$MOBILE_PORT"
	RET_VAL=$?
	while [ $RET_VAL -ne 0 ];do
		logDebug "Host not found, sleeping ${SEARCH_MOBILE_INTERVAL_SEC} seconds..."
		sleep ${SEARCH_MOBILE_INTERVAL_SEC}
		checkForRunningPortServer "$MOBILE_HOST" "$MOBILE_PORT"
		RET_VAL=$?
	done
	logDebug "Server found. Starting backup..."
	logInfo "Mobile found. Backing up data..."
	doBackup && logInfo "Backup successful"
	logDebug "Backup done. Sleeping..."
	[ "$RUN_AS_DAEMON" -eq 0 ] && {
		logDebug "Not running in daemon mode. Exiting."
		exit 0
	}	
	logDebug "Sleeping ${BACKUP_INTERVAL_SEC} seconds before next backup."
	sleep ${BACKUP_INTERVAL_SEC}
done
logInfo "Exiting airback."

exit 0


